---
- name: 'Converge'
  hosts: 'all'
  vars:
    semaphore_debug: true
    semaphore_admin_user_manage: false  # These tasks are not idempotent when using BoltDB
  tasks:
    - name: 'Run role'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
