---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify API availability'
      ansible.builtin.uri:
        url: 'http://semaphore.example.com:3000/api/ping'
        return_content: true
      register: 'reply'
      failed_when: reply['status'] != 200
